language: node_js
node_js:
  - 13

services:
  - docker

before_script:
  - echo "no tests" 
script:
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
  - docker images
  - docker tag udagram-api-feed:latest mwahabsc25/udagram-api-feed:latest
  - docker tag udagram-api-user:latest mwahabsc25/udagram-api-user:latest
  - docker tag udagram-frontend:latest mwahabsc25/udagram-frontend:latest
  - docker tag udagram-reverseproxy:latest mwahabsc25/udagram-reverseproxy:latest       
 after_success:       
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push mwahabsc25/udagram-api-feed
  - docker push mwahabsc25/udagram-api-user
  - docker push mwahabsc25/udagram-frontend
  - docker push mwahabsc25/udagram-reverseproxy
