jobs:
  include:
    - stage: Build
      script:
        - docker build -t udagram-api-feed ./udagram-api-feed
        - docker build -t udagram-api-user ./udagram-api-user
        - docker build -t udagram-frontend ./udagram-frontend
        - docker build -t udagram-reverseproxy ./udagram-reverseproxy
    - stage: Push
      script:
        - docker tag udagram-api-feed mwahabsc25/udagram-api-feed:v1
        - docker tag udagram-api-user mwahabsc25/udagram-api-user:v1
        - docker tag udagram-frontend mwahabsc25/udagram-frontend:v1
        - docker tag udagram-reverseproxy mwahabsc25/udagram-reverseproxy:v1
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push mwahabsc25/udagram-api-feed:v1
        - docker push mwahabsc25/udagram-api-user:v1
        - docker push mwahabsc25/udagram-frontend:v1
        - docker push mwahabsc25/udagram-reverseproxy:v1
